/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyJudgingRouteImport } from './routes/academy.judging'
import { Route as AcademyCoachingRouteImport } from './routes/academy.coaching'
import { Route as AcademyAthletesRouteImport } from './routes/academy.athletes'
import { Route as AboutHistoryRouteImport } from './routes/about.history'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyJudgingRoute = AcademyJudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCoachingRoute = AcademyCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAthletesRoute = AcademyAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AcademyRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/about/history': typeof AboutHistoryRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy/': typeof AcademyIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/about/history': typeof AboutHistoryRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy': typeof AcademyIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/events': typeof EventsIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/about/history': typeof AboutHistoryRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy/': typeof AcademyIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/about/history'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy/'
    | '/directory/'
    | '/events/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/about/history'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy'
    | '/directory'
    | '/events'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/dashboard'
    | '/donate'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/about/history'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy/'
    | '/directory/'
    | '/events/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/judging': {
      id: '/academy/judging'
      path: '/judging'
      fullPath: '/academy/judging'
      preLoaderRoute: typeof AcademyJudgingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/coaching': {
      id: '/academy/coaching'
      path: '/coaching'
      fullPath: '/academy/coaching'
      preLoaderRoute: typeof AcademyCoachingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/athletes': {
      id: '/academy/athletes'
      path: '/athletes'
      fullPath: '/academy/athletes'
      preLoaderRoute: typeof AcademyAthletesRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademyAthletesRoute: typeof AcademyAthletesRoute
  AcademyCoachingRoute: typeof AcademyCoachingRoute
  AcademyJudgingRoute: typeof AcademyJudgingRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAthletesRoute: AcademyAthletesRoute,
  AcademyCoachingRoute: AcademyCoachingRoute,
  AcademyJudgingRoute: AcademyJudgingRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
