/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as ResultsSlugRouteImport } from './routes/results.$slug'
import { Route as EventsWorldChampionship2026RouteImport } from './routes/events.world-championship-2026'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DirectorySlugRouteImport } from './routes/directory.$slug'
import { Route as AcademyTrainingRouteImport } from './routes/academy.training'
import { Route as AcademyJudgingRouteImport } from './routes/academy.judging'
import { Route as AcademyCoachingRouteImport } from './routes/academy.coaching'
import { Route as AcademyAthletesRouteImport } from './routes/academy.athletes'
import { Route as AboutYogaAsASportRouteImport } from './routes/about.yoga-as-a-sport'
import { Route as AboutTechnicalCommitteeRouteImport } from './routes/about.technical-committee'
import { Route as AboutInternationalJudgesRouteImport } from './routes/about.international-judges'
import { Route as AboutInternationalCoachesRouteImport } from './routes/about.international-coaches'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as AboutGovernanceRouteImport } from './routes/about.governance'
import { Route as AboutExecutiveCommitteeRouteImport } from './routes/about.executive-committee'
import { Route as AboutChampionsRouteImport } from './routes/about.champions'
import { Route as AboutAthletesCommissionRouteImport } from './routes/about.athletes-commission'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const ResultsSlugRoute = ResultsSlugRouteImport.update({
  id: '/results/$slug',
  path: '/results/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsWorldChampionship2026Route =
  EventsWorldChampionship2026RouteImport.update({
    id: '/events/world-championship-2026',
    path: '/events/world-championship-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorySlugRoute = DirectorySlugRouteImport.update({
  id: '/directory/$slug',
  path: '/directory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyTrainingRoute = AcademyTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyJudgingRoute = AcademyJudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCoachingRoute = AcademyCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAthletesRoute = AcademyAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AcademyRoute,
} as any)
const AboutYogaAsASportRoute = AboutYogaAsASportRouteImport.update({
  id: '/about/yoga-as-a-sport',
  path: '/about/yoga-as-a-sport',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTechnicalCommitteeRoute = AboutTechnicalCommitteeRouteImport.update({
  id: '/about/technical-committee',
  path: '/about/technical-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutInternationalJudgesRoute =
  AboutInternationalJudgesRouteImport.update({
    id: '/about/international-judges',
    path: '/about/international-judges',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutInternationalCoachesRoute =
  AboutInternationalCoachesRouteImport.update({
    id: '/about/international-coaches',
    path: '/about/international-coaches',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGovernanceRoute = AboutGovernanceRouteImport.update({
  id: '/about/governance',
  path: '/about/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutExecutiveCommitteeRoute = AboutExecutiveCommitteeRouteImport.update({
  id: '/about/executive-committee',
  path: '/about/executive-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutChampionsRoute = AboutChampionsRouteImport.update({
  id: '/about/champions',
  path: '/about/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAthletesCommissionRoute = AboutAthletesCommissionRouteImport.update({
  id: '/about/athletes-commission',
  path: '/about/athletes-commission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sponsorship': typeof SponsorshipRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about/athletes-commission': typeof AboutAthletesCommissionRoute
  '/about/champions': typeof AboutChampionsRoute
  '/about/executive-committee': typeof AboutExecutiveCommitteeRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/international-coaches': typeof AboutInternationalCoachesRoute
  '/about/international-judges': typeof AboutInternationalJudgesRoute
  '/about/technical-committee': typeof AboutTechnicalCommitteeRoute
  '/about/yoga-as-a-sport': typeof AboutYogaAsASportRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy/training': typeof AcademyTrainingRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/world-championship-2026': typeof EventsWorldChampionship2026Route
  '/results/$slug': typeof ResultsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sponsorship': typeof SponsorshipRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about/athletes-commission': typeof AboutAthletesCommissionRoute
  '/about/champions': typeof AboutChampionsRoute
  '/about/executive-committee': typeof AboutExecutiveCommitteeRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/international-coaches': typeof AboutInternationalCoachesRoute
  '/about/international-judges': typeof AboutInternationalJudgesRoute
  '/about/technical-committee': typeof AboutTechnicalCommitteeRoute
  '/about/yoga-as-a-sport': typeof AboutYogaAsASportRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy/training': typeof AcademyTrainingRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/world-championship-2026': typeof EventsWorldChampionship2026Route
  '/results/$slug': typeof ResultsSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/events': typeof EventsIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy': typeof AcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/governance': typeof GovernanceRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/sponsorship': typeof SponsorshipRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/about/athletes-commission': typeof AboutAthletesCommissionRoute
  '/about/champions': typeof AboutChampionsRoute
  '/about/executive-committee': typeof AboutExecutiveCommitteeRoute
  '/about/governance': typeof AboutGovernanceRoute
  '/about/history': typeof AboutHistoryRoute
  '/about/international-coaches': typeof AboutInternationalCoachesRoute
  '/about/international-judges': typeof AboutInternationalJudgesRoute
  '/about/technical-committee': typeof AboutTechnicalCommitteeRoute
  '/about/yoga-as-a-sport': typeof AboutYogaAsASportRoute
  '/academy/athletes': typeof AcademyAthletesRoute
  '/academy/coaching': typeof AcademyCoachingRoute
  '/academy/judging': typeof AcademyJudgingRoute
  '/academy/training': typeof AcademyTrainingRoute
  '/directory/$slug': typeof DirectorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/world-championship-2026': typeof EventsWorldChampionship2026Route
  '/results/$slug': typeof ResultsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/events/': typeof EventsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/join-us'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/sponsorship'
    | '/dashboard'
    | '/about/athletes-commission'
    | '/about/champions'
    | '/about/executive-committee'
    | '/about/governance'
    | '/about/history'
    | '/about/international-coaches'
    | '/about/international-judges'
    | '/about/technical-committee'
    | '/about/yoga-as-a-sport'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy/training'
    | '/directory/$slug'
    | '/events/$slug'
    | '/events/world-championship-2026'
    | '/results/$slug'
    | '/academy/'
    | '/directory/'
    | '/events/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/join-us'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/sponsorship'
    | '/dashboard'
    | '/about/athletes-commission'
    | '/about/champions'
    | '/about/executive-committee'
    | '/about/governance'
    | '/about/history'
    | '/about/international-coaches'
    | '/about/international-judges'
    | '/about/technical-committee'
    | '/about/yoga-as-a-sport'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy/training'
    | '/directory/$slug'
    | '/events/$slug'
    | '/events/world-championship-2026'
    | '/results/$slug'
    | '/academy'
    | '/directory'
    | '/events'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy'
    | '/contact'
    | '/donate'
    | '/governance'
    | '/join-us'
    | '/login'
    | '/privacy'
    | '/rules'
    | '/sponsorship'
    | '/_authenticated/dashboard'
    | '/about/athletes-commission'
    | '/about/champions'
    | '/about/executive-committee'
    | '/about/governance'
    | '/about/history'
    | '/about/international-coaches'
    | '/about/international-judges'
    | '/about/technical-committee'
    | '/about/yoga-as-a-sport'
    | '/academy/athletes'
    | '/academy/coaching'
    | '/academy/judging'
    | '/academy/training'
    | '/directory/$slug'
    | '/events/$slug'
    | '/events/world-championship-2026'
    | '/results/$slug'
    | '/academy/'
    | '/directory/'
    | '/events/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademyRoute: typeof AcademyRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GovernanceRoute: typeof GovernanceRoute
  JoinUsRoute: typeof JoinUsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  SponsorshipRoute: typeof SponsorshipRoute
  AboutAthletesCommissionRoute: typeof AboutAthletesCommissionRoute
  AboutChampionsRoute: typeof AboutChampionsRoute
  AboutExecutiveCommitteeRoute: typeof AboutExecutiveCommitteeRoute
  AboutGovernanceRoute: typeof AboutGovernanceRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutInternationalCoachesRoute: typeof AboutInternationalCoachesRoute
  AboutInternationalJudgesRoute: typeof AboutInternationalJudgesRoute
  AboutTechnicalCommitteeRoute: typeof AboutTechnicalCommitteeRoute
  AboutYogaAsASportRoute: typeof AboutYogaAsASportRoute
  DirectorySlugRoute: typeof DirectorySlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsWorldChampionship2026Route: typeof EventsWorldChampionship2026Route
  ResultsSlugRoute: typeof ResultsSlugRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/results/$slug': {
      id: '/results/$slug'
      path: '/results/$slug'
      fullPath: '/results/$slug'
      preLoaderRoute: typeof ResultsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/world-championship-2026': {
      id: '/events/world-championship-2026'
      path: '/events/world-championship-2026'
      fullPath: '/events/world-championship-2026'
      preLoaderRoute: typeof EventsWorldChampionship2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$slug': {
      id: '/directory/$slug'
      path: '/directory/$slug'
      fullPath: '/directory/$slug'
      preLoaderRoute: typeof DirectorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/training': {
      id: '/academy/training'
      path: '/training'
      fullPath: '/academy/training'
      preLoaderRoute: typeof AcademyTrainingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/judging': {
      id: '/academy/judging'
      path: '/judging'
      fullPath: '/academy/judging'
      preLoaderRoute: typeof AcademyJudgingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/coaching': {
      id: '/academy/coaching'
      path: '/coaching'
      fullPath: '/academy/coaching'
      preLoaderRoute: typeof AcademyCoachingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/athletes': {
      id: '/academy/athletes'
      path: '/athletes'
      fullPath: '/academy/athletes'
      preLoaderRoute: typeof AcademyAthletesRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/about/yoga-as-a-sport': {
      id: '/about/yoga-as-a-sport'
      path: '/about/yoga-as-a-sport'
      fullPath: '/about/yoga-as-a-sport'
      preLoaderRoute: typeof AboutYogaAsASportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/technical-committee': {
      id: '/about/technical-committee'
      path: '/about/technical-committee'
      fullPath: '/about/technical-committee'
      preLoaderRoute: typeof AboutTechnicalCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/international-judges': {
      id: '/about/international-judges'
      path: '/about/international-judges'
      fullPath: '/about/international-judges'
      preLoaderRoute: typeof AboutInternationalJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/international-coaches': {
      id: '/about/international-coaches'
      path: '/about/international-coaches'
      fullPath: '/about/international-coaches'
      preLoaderRoute: typeof AboutInternationalCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/governance': {
      id: '/about/governance'
      path: '/about/governance'
      fullPath: '/about/governance'
      preLoaderRoute: typeof AboutGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/executive-committee': {
      id: '/about/executive-committee'
      path: '/about/executive-committee'
      fullPath: '/about/executive-committee'
      preLoaderRoute: typeof AboutExecutiveCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/champions': {
      id: '/about/champions'
      path: '/about/champions'
      fullPath: '/about/champions'
      preLoaderRoute: typeof AboutChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/athletes-commission': {
      id: '/about/athletes-commission'
      path: '/about/athletes-commission'
      fullPath: '/about/athletes-commission'
      preLoaderRoute: typeof AboutAthletesCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AcademyRouteChildren {
  AcademyAthletesRoute: typeof AcademyAthletesRoute
  AcademyCoachingRoute: typeof AcademyCoachingRoute
  AcademyJudgingRoute: typeof AcademyJudgingRoute
  AcademyTrainingRoute: typeof AcademyTrainingRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAthletesRoute: AcademyAthletesRoute,
  AcademyCoachingRoute: AcademyCoachingRoute,
  AcademyJudgingRoute: AcademyJudgingRoute,
  AcademyTrainingRoute: AcademyTrainingRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademyRoute: AcademyRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GovernanceRoute: GovernanceRoute,
  JoinUsRoute: JoinUsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  SponsorshipRoute: SponsorshipRoute,
  AboutAthletesCommissionRoute: AboutAthletesCommissionRoute,
  AboutChampionsRoute: AboutChampionsRoute,
  AboutExecutiveCommitteeRoute: AboutExecutiveCommitteeRoute,
  AboutGovernanceRoute: AboutGovernanceRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  AboutInternationalCoachesRoute: AboutInternationalCoachesRoute,
  AboutInternationalJudgesRoute: AboutInternationalJudgesRoute,
  AboutTechnicalCommitteeRoute: AboutTechnicalCommitteeRoute,
  AboutYogaAsASportRoute: AboutYogaAsASportRoute,
  DirectorySlugRoute: DirectorySlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsWorldChampionship2026Route: EventsWorldChampionship2026Route,
  ResultsSlugRoute: ResultsSlugRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
